name: Application Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'auto_heal.sh'
      - 'app/**'
      - '.github/workflows/deploy.yml'
  workflow_run:
    workflows: ["Infra Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
   # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform (for output)
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Get EC2 Public IP
        id: ec2_ip
        run: echo "IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y docker.io docker-compose git

            if [ ! -d "Self-Healing-Infrastructure" ]; then
              git clone https://github.com/hs2002-18/Self-Healing-Infrastructure.git
            fi

            cd Self-Healing-Infrastructure

            docker-compose down
            docker-compose up -d

            chmod +x auto_heal.sh
            nohup ./auto_heal.sh > heal.log 2>&1 &
